"""
Django settings for the Soul Font project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Every setting below reads an environment variable and falls back to the old local
# default, so `manage.py runserver` on a laptop behaves exactly as it did while a
# deployment configures itself entirely through the environment.

# The fallback is the key that has been committed to this repo since the project began.
# Treat it as public: set DJANGO_SECRET_KEY anywhere the site is reachable.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-i3f4iyw_$a+596*=vexcwu37*gu0ponf91z!&5w^)du3&$-pcu',
)

DEBUG = os.environ.get('DJANGO_DEBUG', '1').lower() not in ('0', 'false', 'no')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pybo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Everything the app writes and must keep — the database and the generated fonts —
# lives under one root, so a deployment can point it at a mounted volume. Unset, it is
# the project directory and the layout is unchanged.
DATA_DIR = Path(os.environ.get('SOULFONT_DATA_DIR', BASE_DIR))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}

# Unset, Django sends @login_required to /accounts/login/, which this project has never had —
# so a signed-out visitor following a link to a font's page got a 404 instead of the log-in
# window. The names are this app's own.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'desktop'

# Password validation — deliberately empty, so no strength rules are enforced on sign-up.
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

# The dev server serves static files itself; gunicorn does not, and there is no nginx in
# front of it here. WhiteNoise fills that gap. Guarded so a virtualenv without it (any
# checkout predating this) still starts — it is only needed off the dev server.
try:
    import whitenoise  # noqa: F401
except ImportError:
    pass
else:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        # Compressed, but deliberately not the *manifest* variant: that one raises at
        # request time if any file referenced from CSS is missing, which would take the
        # whole site down over a stylesheet typo.
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
    }

ALLOWED_HOSTS = [h.strip() for h in
                 os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]

# Django 4 rejects a cross-origin POST unless the origin is listed here, and behind a
# platform's TLS terminator every POST looks cross-origin. Without this, logging in on
# the deployed site fails with "CSRF verification failed" while working locally.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in
                        os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
                        if o.strip()]

# The proxy terminates TLS and forwards plain HTTP, so Django needs telling that the
# original request was secure — otherwise it builds http:// redirects on an https:// site.
if os.environ.get('DJANGO_BEHIND_PROXY', '').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(DATA_DIR, 'media')