# Generated by Django 5.1.7 on 2025-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_rename_description_font_font_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='font_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
