# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_userdata_author_userdata_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
