# Generated by Codex on 2026-06-22

from django.db import migrations, models


def replace_korean_default(apps, schema_editor):
    UserData = apps.get_model('pybo', 'UserData')
    UserData.objects.filter(font_name='기본폰트').update(font_name='Default Font')


def restore_korean_default(apps, schema_editor):
    UserData = apps.get_model('pybo', 'UserData')
    UserData.objects.filter(font_name='Default Font').update(font_name='기본폰트')


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_userdata_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='font_name',
            field=models.CharField(default='Default Font', max_length=100),
        ),
        migrations.RunPython(replace_korean_default, restore_korean_default),
    ]
