# Generated by Django 4.2.23 on 2026-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_default_font_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ttf_file_bold',
            field=models.FileField(blank=True, null=True, upload_to='ttf_files/'),
        ),
    ]
