# Generated by Django 4.2.23 on 2026-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_alter_userdata_options_userdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
