# Generated by Django 4.2.23 on 2026-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_alter_userdata_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='status_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='status_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='status_stage',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
