# Generated by Django 4.2.23 on 2026-08-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0016_userdata_status_userdata_status_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pybo.userdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FontExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8, unique=True)),
                ('stroke_adjust', models.SmallIntegerField(default=0)),
                ('letter_spacing_units', models.SmallIntegerField(default=0)),
                ('glyph_scale', models.FloatField(default=1.0)),
                ('ttf_file', models.FileField(blank=True, null=True, upload_to='ttf_files/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('status_stage', models.CharField(blank=True, default='', max_length=60)),
                ('status_percent', models.PositiveSmallIntegerField(default=0)),
                ('status_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='pybo.userdata')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('font', 'user'), name='uniq_like_font_user'),
        ),
    ]
