C: 32
charset_path: data/charset/korean2350.txt
checkpoint: checkpoints/korean-handwriting.pth
language: kor
n_comp_types: 3
n_comps: 68
num_font_samples: 1
output_dir: static/outputs/user_45
style_chars:
- 각
- 깪
- 냓
- 댼
- 떥
- 렎
- 멷
- 볠
- 뽉
- 솲
- 쐛
- 욄
- 죭
- 쭲
- 춣
- 퀨
- 튑
- 퓺
- 흣
- 읬
- 잉
- 잊
- 잋
- 잌
- 잍
- 잎
- 잏
- 이
style_imgs:
- style/user_45/cleaned/uniAC00.png
- style/user_45/cleaned/uniAC01.png
- style/user_45/cleaned/uniAC02.png
- style/user_45/cleaned/uniAC03.png
- style/user_45/cleaned/uniAC04.png
- style/user_45/cleaned/uniAC05.png
- style/user_45/cleaned/uniAC06.png
- style/user_45/cleaned/uniAC07.png
- style/user_45/cleaned/uniAC08.png
- style/user_45/cleaned/uniAC09.png
- style/user_45/cleaned/uniAC0A.png
- style/user_45/cleaned/uniAC0B.png
- style/user_45/cleaned/uniAC0C.png
- style/user_45/cleaned/uniAC0D.png
- style/user_45/cleaned/uniAC0E.png
- style/user_45/cleaned/uniAC0F.png
- style/user_45/cleaned/uniAC10.png
- style/user_45/cleaned/uniAC11.png
- style/user_45/cleaned/uniAC12.png
- style/user_45/cleaned/uniAC13.png
- style/user_45/cleaned/uniAC14.png
- style/user_45/cleaned/uniAC15.png
- style/user_45/cleaned/uniAC16.png
- style/user_45/cleaned/uniAC17.png
- style/user_45/cleaned/uniAC18.png
- style/user_45/cleaned/uniAC19.png
- style/user_45/cleaned/uniAC1A.png
- style/user_45/cleaned/uniAC1B.png
target_chars:
- 워
- 권
- 뭐
- 가
template_cell_count: 112
template_full_cell_count: 112
template_layout_version: kor-28-plus-extra-v3-ssyweo
