# Generated by Django 5.1.7 on 2025-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_font_delete_answer_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='description',
            new_name='font_description',
        ),
        migrations.RenameField(
            model_name='font',
            old_name='font_file',
            new_name='ttf_file',
        ),
        migrations.RemoveField(
            model_name='font',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='font',
            name='quote',
        ),
        migrations.AddField(
            model_name='font',
            name='text',
            field=models.CharField(default='No Description', max_length=255),
        ),
    ]
