# Generated by Django 3.2.18 on 2025-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_alter_font_font_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
                ('templates', models.FileField(upload_to='templates/')),
                ('ttf_file', models.FileField(upload_to='ttf_files/')),
                ('quote', models.TextField()),
            ],
        ),
    ]
