# Generated by Django 4.2.23 on 2026-06-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='license_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='license_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='version',
            field=models.CharField(blank=True, default='1.000', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='font_name',
            field=models.CharField(default='기본폰트', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ttf_file',
            field=models.FileField(default='ttf_files/MaruBuri-Regular.ttf', upload_to='ttf_files/'),
        ),
    ]
