# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_userdata_ttf_file_bold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ttf_file_light',
            field=models.FileField(blank=True, null=True, upload_to='ttf_files/'),
        ),
    ]
